language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - g++-6
    - libsnappy-dev
    - zlib1g-dev
    - libbz2-dev

env:
  - CC=gcc-5 CXX=g++-5
  - CC=gcc-6 CXX=g++-6

script:
  - $CC -v
  - $CXX -v
  - cargo build --verbose -j1
  - cargo test --verbose -j1
