[package]
name = "rocksdb-sys"
version = "0.1.0"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
license = "MIT/Apache-2.0"
description = "Native bindings to the rocksdb library"

[dependencies]
libc = "0.1.8"
